-   id: bazel-buildifier
    name: 'bazel buildifier'
    entry: buildifier
    files: 'BUILD.bazel|BUILD|WORKSPACE'
    language: 'system'
    description: "Runs `buildifier`, requires bazel buildifier"
-   id: go-imports
    name: 'go imports'
    entry: run-go-imports.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go imports`, requires golang"
-   id: go-critic
    name: 'go-critic'
    entry: run-go-critic.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go-critic`, requires go-critic"
-   id: golangci-lint
    name: 'golangci-lint'
    entry: run-golangci-lint.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `golangci-lint`, requires golangci-lint"
-   id: golangci-lint-conf
    name: 'golangci-lint-conf'
    entry: run-golangci-lint-conf.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `golangci-lint` read local config file, requires golangci-lint"
